### ISSUE TITLE
designate-certmanager-designate-certmanager-webhook pod stuck

### ISSUE THREAD

**Issue by andrijaperovic** [syseleven/designate-certmanager-webhook#5]
Hi, 

Thanks so much for the implementation! This is incredibly helpful and neat to extend native certmanager capability. 
I ran into a bit of a hiccup, after installing the helm 2 chart and creating the cloud-credentials secret and clusterissuer, I am seeing a behavior where the init container of the certmanager-webhook pod is completely stuck and emits no logs: 

`kubectl get pods -n cert-manager                                     master@999cbea ✔
NAME                                                              READY   STATUS     RESTARTS   AGE
designate-certmanager-designate-certmanager-webhook-599d5bb4v5r   0/1     Init:0/2   0          7m3s`

If I do a describe on the pod I see that that it has started the container but appears to be in a hung state: 

```
Events:
  Type    Reason     Age        From                                        Message
  ----    ------     ----       ----                                        -------
  Normal  Scheduled  <unknown>  default-scheduler                           Successfully assigned cert-manager/designate-certmanager-designate-certmanager-webhook-599d5bb4v5r to aks-agentpool-39422221-vmss000002
  Normal  Pulling    10m        kubelet, aks-agentpool-39422221-vmss000002  Pulling image "alpine:latest"
  Normal  Pulled     10m        kubelet, aks-agentpool-39422221-vmss000002  Successfully pulled image "alpine:latest"
  Normal  Created    10m        kubelet, aks-agentpool-39422221-vmss000002  Created container wait-for-tls-secret
  Normal  Started    10m        kubelet, aks-agentpool-39422221-vmss000002  Started container wait-for-tls-secret
```

Can you describe a little bit about this init container, and what might be the issue? In the deployment.yaml of the helm chart I see that is runs a while loop until a condition is satisfied: 
`          command:
            - /bin/sh
          args:
            - -c
            - "while [ ! -f /tls/tls.key ]; do sleep 5; done"`

It appears that tls.key might not be getting mounted. Would there be any specific reason for that? 
Thank you!

**Comment by andrijaperovic** [comment]
```
kubectl get secret -n cert-manager                                   master@999cbea ✔
NAME                                                              TYPE                                  DATA   AGE
cloud-credentials                                                 Opaque                                6      34m
default-token-hptln                                               kubernetes.io/service-account-token   3      34m
designate-certmanager-designate-certmanager-webhook-token-2dhsb   kubernetes.io/service-account-token   3      23m
istio.default                                                     istio.io/key-and-cert                 3      34m
istio.designate-certmanager-designate-certmanager-webhook         istio.io/key-and-cert                 3      23m
```

**Comment by frittenlab** [comment]
@andrijaperovic Which version of cert-manager are you using? We are currently working on providing an updated version. To support the 0.15.x versions of cert-manager. The current version should work up to 0.10.x

**Comment by andrijaperovic** [comment]
Hi @frittenlab I applied the yaml for the 0.10 CRDs of cert-manager only, otherwise I believe it complains about missing apiVersion of CRD.

**Comment by frittenlab** [comment]
I just tested the current version of the webhook with this cert-manager version:

quay.io/jetstack/cert-manager-controller:v0.10.1

This secret was created during the installation:

syseleven-cert-manager-webhook-tls              kubernetes.io/tls                     3      102s

We are planning on releasing the new version for the current cert-manager versions tomorrow.

**Comment by andrijaperovic** [comment]
Hi @frittenlab,

Please find the instructions which I used to install the webhook on my cluster and pre-requisites: 

Helm2 init and and upgrade
`
helm2 init
$HELM_HOME has been configured at ~/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)

helm2 init --service-account tiller --upgrade
$HELM_HOME has been configured at ~/.helm
Tiller (the Helm server-side component) has been updated to gcr.io/kubernetes-helm/tiller:v2.16.3 
`

Adding jetstack helm repo: 

`
helm2 repo add jetstack https://charts.jetstack.io
"jetstack" has been added to your repositories

helm2 repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
`

Installing cert-manager v0.10.1:

`
helm2 install --name cert-manager --namespace cert-manager --version v0.10.1 jetstack/cert-manager
NAME:   cert-manager
LAST DEPLOYED: Tue Jul 21 15:50:27 2020
NAMESPACE: cert-manager
STATUS: DEPLOYED
RESOURCES:
==> v1/ClusterRole
NAME                                    AGE
cert-manager-edit                       0s
cert-manager-view                       0s
cert-manager-webhook:webhook-requester  0s
==> v1/Deployment
NAME                     AGE
cert-manager             0s
cert-manager-cainjector  0s
cert-manager-webhook     0s
==> v1/Pod(related)
NAME                                     AGE
cert-manager-58f7b54fcd-fhwwg            0s
cert-manager-cainjector-c9855769f-nkm4m  0s
cert-manager-webhook-7c6f9dfd8b-db56r    0s
==> v1/Service
NAME                  AGE
cert-manager          0s
cert-manager-webhook  0s
==> v1/ServiceAccount
NAME                     AGE
cert-manager             0s
cert-manager-cainjector  0s
cert-manager-webhook     0s
==> v1beta1/APIService
NAME                                AGE
v1beta1.webhook.certmanager.k8s.io  0s
==> v1beta1/ClusterRole
NAME                                    AGE
cert-manager-cainjector                 0s
cert-manager-controller-certificates    0s
cert-manager-controller-challenges      0s
cert-manager-controller-clusterissuers  0s
cert-manager-controller-ingress-shim    0s
cert-manager-controller-issuers         0s
cert-manager-controller-orders          0s
cert-manager-leaderelection             0s
==> v1beta1/ClusterRoleBinding
NAME                                    AGE
cert-manager-cainjector                 0s
cert-manager-controller-certificates    0s
cert-manager-controller-challenges      0s
cert-manager-controller-clusterissuers  0s
cert-manager-controller-ingress-shim    0s
cert-manager-controller-issuers         0s
cert-manager-controller-orders          0s
cert-manager-leaderelection             0s
cert-manager-webhook:auth-delegator     0s
==> v1beta1/MutatingWebhookConfiguration
NAME                  AGE
cert-manager-webhook  0s
==> v1beta1/RoleBinding
NAME                                                AGE
cert-manager-webhook:webhook-authentication-reader  0s
==> v1beta1/ValidatingWebhookConfiguration
NAME                  AGE
cert-manager-webhook  0s
NOTES:
cert-manager has been deployed successfully!
In order to begin issuing certificates, you will need to set up a ClusterIssuer
or Issuer resource (for example, by creating a 'letsencrypt-staging' issuer).
More information on the different types of issuers and how to configure them
can be found in our documentation:
https://docs.cert-manager.io/en/latest/reference/issuers.html
For information on how to configure cert-manager to automatically provision
Certificates for Ingress resources, take a look at the `ingress-shim`
documentation:
https://docs.cert-manager.io/en/latest/reference/ingress-shim.html
`

Helm2 chart installation of designate-certmanager-webhook after cloning repository:

`
helm2 install --name designate-certmanager --namespace=cert-manager designate-certmanager-webhook                                                                                                                           0.2.9@bf4a858 ✔
NAME:   designate-certmanager
LAST DEPLOYED: Tue Jul 21 15:59:19 2020
NAMESPACE: cert-manager
STATUS: DEPLOYED
RESOURCES:
==> v1/ClusterRole
NAME                                                               AGE
designate-certmanager-designate-certmanager-webhook:domain-solver  1s
==> v1/ClusterRoleBinding
NAME                                                                AGE
designate-certmanager-designate-certmanager-webhook:auth-delegator  1s
designate-certmanager-designate-certmanager-webhook:domain-solver   1s
==> v1/ConfigMap
NAME                                                            AGE
designate-certmanager-designate-certmanager-webhook-apiservice  1s
==> v1/Deployment
NAME                                                 AGE
designate-certmanager-designate-certmanager-webhook  1s
==> v1/Pod(related)
NAME                                                             AGE
designate-certmanager-designate-certmanager-webhook-599d5bz4jvx  1s
==> v1/RoleBinding
NAME                                                                               AGE
designate-certmanager-designate-certmanager-webhook:webhook-authentication-reader  1s
==> v1/Service
NAME                                                 AGE
designate-certmanager-designate-certmanager-webhook  1s
==> v1/ServiceAccount
NAME                                                 AGE
designate-certmanager-designate-certmanager-webhook  1s
==> v1alpha2/Certificate
NAME                                                             AGE
designate-certmanager-designate-certmanager-webhook-ca           1s
designate-certmanager-designate-certmanager-webhook-webhook-tls  1s
==> v1alpha2/Issuer
NAME                                                          AGE
designate-certmanager-designate-certmanager-webhook-ca        1s
designate-certmanager-designate-certmanager-webhook-selfsign  1s
`

State of cert-manager namespace after installation:

`
kubectl get pods -n cert-manager                                                                                                                                                                                            0.2.9@bf4a858 ✔
NAME                                                              READY   STATUS     RESTARTS   AGE
cert-manager-58f7b54fcd-fhwwg                                     1/1     Running    0          34m
cert-manager-cainjector-c9855769f-bvtgk                           1/1     Running    0          25m
cert-manager-webhook-7c6f9dfd8b-db56r                             1/1     Running    1          34m
designate-certmanager-designate-certmanager-webhook-599d5bz4jvx   0/1     Init:0/2   0          25m

Events:
  Type    Reason     Age        From                                        Message
  ----    ------     ----       ----                                        -------
  Normal  Scheduled  <unknown>  default-scheduler                           Successfully assigned cert-manager/designate-certmanager-designate-certmanager-webhook-599d5bz4jvx to aks-agentpool-39422221-vmss000000
  Normal  Pulled     26m        kubelet, aks-agentpool-39422221-vmss000000  Container image "alpine:latest" already present on machine
  Normal  Created    26m        kubelet, aks-agentpool-39422221-vmss000000  Created container wait-for-tls-secret
  Normal  Started    26m        kubelet, aks-agentpool-39422221-vmss000000  Started container wait-for-tls-secret
`

List of secrets on the cert-manager namespace: 

`
kubectl get secrets -n cert-manager                                                                                                                                                                                         0.2.9@bf4a858 ✔
NAME                                                              TYPE                                  DATA   AGE
cert-manager-cainjector-token-pwjl8                               kubernetes.io/service-account-token   3      35m
cert-manager-token-4zd8f                                          kubernetes.io/service-account-token   3      35m
cert-manager-webhook-ca                                           kubernetes.io/tls                     3      35m
cert-manager-webhook-tls                                          kubernetes.io/tls                     3      35m
cert-manager-webhook-token-t4x2n                                  kubernetes.io/service-account-token   3      35m
cloud-credentials                                                 Opaque                                6      24h
default-token-bgrd6                                               kubernetes.io/service-account-token   3      24h
designate-certmanager-designate-certmanager-webhook-token-r46hj   kubernetes.io/service-account-token   3      26m
istio.cert-manager                                                istio.io/key-and-cert                 3      35m
istio.cert-manager-cainjector                                     istio.io/key-and-cert                 3      35m
istio.cert-manager-webhook                                        istio.io/key-and-cert                 3      35m
istio.default                                                     istio.io/key-and-cert                 3      24h
istio.designate-certmanager-designate-certmanager-webhook         istio.io/key-and-cert                 3      26m
`

As you can see, the secret has not been generated and the webhook pod is still stuck in an initializing state.

**Comment by andrijaperovic** [comment]
@frittenlab  any ideas on what might be wrong?

**Comment by frittenlab** [comment]
You should not need any additional CRD's to run the webhook. We released the new version 0.29 for cert-manager 0.15.x this morning. You can give it a try if you like.

**Comment by andrijaperovic** [comment]
Thanks @frittenlab . 
I pulled the most recent changes and re-installed 0.15.1 cert-manager, however when attempting to re-install the local helm-chart for designate-certmanager-webhook, encountered some issues: 

```
helm2 install --name designate-certmanager --namespace=cert-manager designate-certmanager-webhook

Error: release designate-certmanager failed: Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=30s: x509: certificate signed by unknown authority
```

**Comment by andrijaperovic** [comment]
I was able to fix the above issue by passing `installCRDs=true` during helm2 cert-manager installation:
```
helm2 install --name cert-manager --namespace cert-manager --version v0.15.1 jetstack/cert-manager --set installCRDs=true
```

However, the issue still persists, even in the 0.15.1 cert-manager with 0.29 designate-certmanager-webhook:
```
kubectl get pods -n cert-manager                             master@47a3538 ✔
NAME                                                              READY   STATUS            RESTARTS   AGE
cert-manager-764596ff78-qlw85                                     1/1     Running           0          115s
cert-manager-cainjector-654d996c89-bkvlz                          1/1     Running           0          114s
cert-manager-webhook-54bd4dccdb-56k6f                             1/1     Running           0          115s
designate-certmanager-designate-certmanager-webhook-599d5bqpjjm   0/1     PodInitializing   0          75s
```

**Comment by andrijaperovic** [comment]
Installation went through fine now! 
Now i'm getting an i/o timeout on the OS_AUTH_URL, which is expected.
Thanks so much @frittenlab !
